// = 商品
export const PAGING_PRODUCT = 'pagingProduct';
export const GET_PRODUCT = 'getProduct';
// = 购物车
export const ADD_MY_SHOPPING_CART = 'addMyShoppingCart';
export const UPDATE_MY_SHOPPING_CART = 'updateMyShoppingCart';
export const DELETE_MY_SHOPPING_CART = 'deleteMyShoppingCart';
export const PAGING_MY_SHOPPING_CART = 'pagingMyShoppingCart';
// = 收货地址
export const ADD_MY_ADDRESS = 'addMyAddress';
export const GET_MY_ADDRESS = 'getMyAddress';
export const UPDATE_MY_ADDRESS = 'updateMyAddress';
export const DELETE_MY_ADDRESS = 'deleteMyAddress';
export const PAGING_MY_ADDRESS = 'pagingMyAddress';
// = 省/市/县
export const GET_PROVINCE = 'getProvince';
export const GET_CITY = 'getCity';
export const GET_COUNTY = 'getCounty';

// = 创建订单
export const CREATE_ORDER = 'createOrder';
export const CONFIRM_MY_ORDER = 'confirmMyOrder';
// = 分页查询我的订单列表
export const PAGING_MY_ORDER = 'pagingMyOrder';
export const GET_MY_ORDER = 'getMyOrder';
export const CANCEL_MY_ORDER = 'cancelMyOrder';
// = 退款申请
export const CREATE_REFUND_APPLY = 'createRefundApply';
// = 订单估价
export const CALC_ORDER = 'calcOrder';
// = 交易单
export const GET_WAIT_PAYMENT_TRADE = 'getWaitPaymentOrder';
export const PAY_TRADE = 'payTrade';
// = 登录
export const LOGIN = 'login';
// = 获取用户信息
export const GET_USER_INFO = 'getUserInfo';
// = 优惠券
export const PAGING_MY_COUPON = 'pagingMyCoupon';


export const GET_AVATAR_URL = 'getAvatarUrl';